cc_test(
  name = "basic",
  srcs = ["basic_test.cc"],
  deps = [
    "@googletest//:gtest_main",
  ],
)

cc_test(
  name = "hello",
  srcs = ["hello_test.cc"],
  deps = [
   "//main:hello",
   "@googletest//:gtest_main",
  ],
)

